name: CI
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - if: matrix.os == 'ubuntu-latest'
      name: Set up PATH on Linux
      run: echo "/usr/local/texlive/bin/x86_64-linux" >> $GITHUB_PATH

    - if: matrix.os == 'macos-latest'
      name: Set up PATH on macOS
      run: echo "/usr/local/texlive/bin/universal-darwin" >> $GITHUB_PATH

    - if: matrix.os == 'windows-latest'
      name: Set up PATH on Windows
      shell: bash
      run: echo "C:\texlive\bin\windows" >> $GITHUB_PATH

    - if: matrix.os != 'windows-latest'
      name: Installation test on Unix
      run: |
        sudo ./install-tl -no-gui -profile=.github/workflows/unix.profile
        tlmgr --version

    - if: matrix.os == 'windows-latest'
      name: Installation test on Windows
      run: |
        echo y | .\install-tl-windows.bat -v -no-gui -profile=.github/workflows/windows.profile
        tlmgr.bat --version
